#ifndef ALIENHACK_MODEL_VERSION_HPP
#define	ALIENHACK_MODEL_VERSION_HPP


#define GAMEMODEL_VERSION_MAJOR			0
#define GAMEMODEL_VERSION_MINOR			9
#define GAMEMODEL_VERSION_INCREMENTAL	1
#define GAMEMODEL_VERSION_STR	"0.9.1 beta"

#define GAMEMODEL_SAVE_LAST_COMPATIBLE_MAJOR		0
#define GAMEMODEL_SAVE_LAST_COMPATIBLE_MINOR		9
#define GAMEMODEL_SAVE_LAST_COMPATIBLE_INCREMENTAL	1

#endif
